// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArz7xQr70ID8lLgWi3KLER0OGxBkcy2Cg',
    appId: '1:758223478729:web:47ed77f2a473c4956ad218',
    messagingSenderId: '758223478729',
    projectId: 'grocery-app-b8c56',
    authDomain: 'grocery-app-b8c56.firebaseapp.com',
    storageBucket: 'grocery-app-b8c56.appspot.com',
    measurementId: 'G-KP3TZR1V57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7SiIRZFHsV6q2V7Nu0OKI96iw1Qa8x6k',
    appId: '1:758223478729:android:48da12d8a9008d086ad218',
    messagingSenderId: '758223478729',
    projectId: 'grocery-app-b8c56',
    storageBucket: 'grocery-app-b8c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-f0h_OOt3VRctqnwwqMOIeUKRUEErDY',
    appId: '1:758223478729:ios:daacb9ef32a4d9666ad218',
    messagingSenderId: '758223478729',
    projectId: 'grocery-app-b8c56',
    storageBucket: 'grocery-app-b8c56.appspot.com',
    iosClientId: '758223478729-5jiujh8kssio1uvcmna928cia0to6rb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneStopGrocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY-f0h_OOt3VRctqnwwqMOIeUKRUEErDY',
    appId: '1:758223478729:ios:daacb9ef32a4d9666ad218',
    messagingSenderId: '758223478729',
    projectId: 'grocery-app-b8c56',
    storageBucket: 'grocery-app-b8c56.appspot.com',
    iosClientId: '758223478729-5jiujh8kssio1uvcmna928cia0to6rb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneStopGrocery',
  );
}
